[package]
name = "side-lib"
version = "0.2.0"
authors = ["Rotem Yaari <vmalloc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel_migrations = "1.4.0"
diesel = "1.4.0"
